# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
array = np.zeros(10)

#### Create an array of 10 ones

In [3]:
array1 = np.ones(10)

#### Create an array of 10 fives

In [9]:
array2 = np.full((1,10), 5)
print (array2)

[[5 5 5 5 5 5 5 5 5 5]]


#### Create an array of the integers from 10 to 50

In [12]:
array3=np.arange(10,51,1)
print(array3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [14]:
array4=np.arange(10,52,2)
print(array4)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


##find the memory size of any array

In [16]:
a = [2,4,5,6,7,8]
b = np.array(a)
print(b.size)

6


#### Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
a = np.array([range(i, i + 3) for i in [0, 3, 5]])

print(a)

[[0 1 2]
 [3 4 5]
 [5 6 7]]


#### Create a 3x3 identity matrix

In [18]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [23]:
rand_num = np.random.normal(0,1,1)
print(rand_num)

[-1.90325522]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [26]:
rand_num2 = np.random.normal(0,1,25)
print(rand_num2)

[ 0.48163308 -0.40022678 -1.09454726  0.67343546  1.29197935  0.11897894
  0.31584578 -1.28116754  0.58892309 -2.37341132 -0.70994768  1.33644988
 -0.0918987  -0.84807963  0.55020909 -1.00377537 -1.17355039 -0.31943039
  1.62631991  0.49834786  0.84062247 -0.37143591 -0.7366541   0.26027796
  2.35232629]


#### Create the following matrix:

In [28]:
arr = np.arange(0.01, 1.01, 0.01)
arr = arr.reshape(10, 10)
print(arr)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [27]:
l = np.linspace(0, 1, 20)
print(l)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [40]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [31]:
output_arr = mat[2:, 1:]

print(output_arr)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [32]:
result = mat[3, 4]

print(result)

20


In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [47]:
output_arr = mat[0:3, 1:2]

print(output_arr)

[[ 2]
 [ 7]
 [12]]


In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [49]:
output_arr = mat[-1, :]

print(output_arr)

[21 22 23 24 25]


In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [50]:
output_arr = mat[-2:, :]

print(output_arr)

[[16 17 18 19 20]
 [21 22 23 24 25]]


### Now do the following

#### Get the sum of all the values in mat

In [51]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [52]:
std = np.std(mat)

print(std)

7.211102550927978


#### Get the sum of all the columns in mat

In [53]:
sum_columns = np.sum(mat, axis=0)
print(sum_columns)

[55 60 65 70 75]


####Create a 10*10  matrix with 1 on the border and 0 inside

In [55]:
matrix = np.zeros((10, 10))
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1
print (matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### find common values between two arrays

In [56]:
x1 = np.array([0, 2, 2, 2, 4, 5, 1, 4, 8, 5])
x2 = np.array([2, 2, 3, 4, 7, 4, 6, 9, 4, 8])

In [57]:
common_values = np.intersect1d(x1, x2)

print(common_values)

[2 4 8]


####You can use flatten to flatten your array into a 1D array

In [58]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [59]:
x_flat = x.flatten()

print(x_flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Great Job!